### ISSUE TITLE
Laser Energy motor

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/Bug-Reports-and-Requests#11]
**Feature Request**
old xpppython has n 'lxe' motor that read in a text file and uses that to work in 'energy' units rather than degrees for a ND wheel in the laser setup.

**Existing Alternatives**
Use paper table as in past?

**Context**
Look at implementation in old XPP/XCS beamline python

**Comment by ZLLentz** [comment]
Some notes:
- lxe is defined in three different ways in `/reg/g/pcds/pyps/xpp/dev/xpp/beamline.py`
- lxe is also defined in three different ways in `/reg/g/pcds/pyps/xcs/dev/xcs/beamline.py` 
- lxe relies on the `blbase`/`blinst`/`blutil` modules saved locally in these areas

**Comment by klauer** [comment]
I think I have enough information to make a go at this. 

Are there any feature requests from those who have used this, or is a truly *identical-to-the-old-version* what they want?

**Comment by klauer** [comment]
@silkenelson I'm not sure I'm clear as to the requirements here, but I believe I've implemented support for the table-based 'lxe' motor and plotting in https://github.com/pcdshub/pcdsdevices/pull/506. If you have any input, please do let me know.
