### ISSUE TITLE
EPICS archiver implementation

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/Bug-Reports-and-Requests#18]
**Feature Request**
We had a very nice connection to the EPICS archiver in old beamline python.

**Existing Alternatives**
Use old beamline python.

**Context**
general motion debugging and other debugging (e.g. current history for detector channels,....)

**Comment by ZLLentz** [comment]
This also already exists. Which hutch is missing it so we can investigate?

**Comment by silkenelson** [comment]
I'll check when I have time. The last time I tried, it did not work and I had this array ' not implemented error'. This was tracked in a Trello card that did not get updated after it first not working. I will admit that I did not have the time to test everything when closing the card and moving issues here to at least a more central location.

**Comment by ZLLentz** [comment]
Right, thanks for the reminder. This is linked to https://github.com/pcdshub/archapp/issues/6
