### ISSUE TITLE
PIM Classes Fail in dev Python

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/Bug-Reports-and-Requests#19]
**Bug Report**

PIM classes don't connect in dev python due to a bad comparison. See the screenshot below. This goes away in pcds-3.2.0.
**Expected Behavior**

PIM classes should connect. 
**Context**

This prevents MEC from running the dev environment with the PIMs.
**Steps To Reproduce**

1. Run hutch python with dev environment.
2. Instantiate a PIM with prefix 'MEC:PIM3'
3. Watch it fail.
4. Switch to pcds-3.2.0
5. Instantiate PIM as before.
6. Watch the PIM happily move. 

**Your Environment**

dev python vs pcds-3.2.0, testing in mecpython

**Screenshots**
![image](https://user-images.githubusercontent.com/29102919/90158676-236bbf80-dd44-11ea-8872-80b1bf44c384.png)

**Comment by ZLLentz** [comment]
Bizarre. I wonder what changed to make `old_value` an `object`. I'll look under the hood.

**Comment by ZLLentz** [comment]
The starting values for signals in `ophyd` have changed from `None` to `DEFAULT_EPICSSIGNAL_VALUE`. Our classes will need to updated accordingly.

**Comment by ZLLentz** [comment]
Walking back a bit: the patch I was going to do has already been done, and I cannot reproduce this issue.
https://github.com/pcdshub/pcdsdevices/blob/33ab6393fcd1529a24a15606f4764c95241ab50f/pcdsdevices/epics_motor.py#L245-L251

```
$ source dev_conda
$ ipython
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pcdsdevices.device_types import PIM
/reg/g/pcds/pyps/conda/py36/envs/dev/lib/python3.6/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/reg/g/pcds/pyps/conda/py36/envs/dev/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)

In [2]: pim = PIM('MEC:PIM3', name='pim')

In [3]: import pcdsdevices

In [4]: pcdsdevices.__file__
Out[4]: '/reg/g/pcds/pyps/apps/dev/pythonpath/pcdsdevices/__init__.py'
```

The file in your traceback is not the dev file. How are you setting up the dev conda environment?

**Comment by slactjohnson** [comment]
Hmm, weird. I was setting my CONDA_ENVNAME to "dev" in mecenv. I'll take a closer look.

**Comment by slactjohnson** [comment]
Looks like /reg/g/pcds/pyps/conda/dev_conda is explicitly setting PYTHONPATH to the path you show. When I simply do conda activate dev (as is done in the mecenv file, as currently written), I get a different path for pcdsdevices:

In [1]: import pcdsdevices                                                                                                                                      

In [2]: pcdsdevices.__file__                                                                                                                                    
Out[2]: '/reg/g/pcds/pyps/conda/py36/envs/dev/lib/python3.6/site-packages/pcdsdevices/__init__.py'

In [3]:  

Should I be pointing mecpython to dev a different way?

**Comment by ZLLentz** [comment]
The dev environment works by munging the PYTHONPATH to add master branch versions of every repo. The hutch python hutch directories also have local devs (and a common local dev) that work the same way.

If you want to include these dev overrides in a hutch python env, edit the PYTHONPATH appropriately.

It's probably time for a round of tag/release...

**Comment by slactjohnson** [comment]
OK, thanks. I think we can close this then.

**Comment by klauer** [comment]
We could make a python meta-package which adjusts PYTHONPATH to our dev paths on conda activate (activate/deactivate script hooks, like we use for typhos/pydm/etc designer settings). I think that's probably unnecessary though.

**Comment by ZLLentz** [comment]
In general we should consider using meta packages for env vars, it would avoid situations like this. I was also considering as such for the pydm stylesheets.
