### ISSUE TITLE
Saving of virtual motor positions as actual EPICS PVs.

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/Bug-Reports-and-Requests#20]
**Feature Request**
Virtual motors w/ positions saved as actual PVs (can be hosted in notepad PV)
Might be implemented?

**Existing Alternatives**
exists in old python

**Context**
We are converting e.g. a stage position into a laser-xray delay in sec. In addition to the stages values, we also define PVs for the physically meaningful virtual motor position so that this can be saved in the DAQ epicsarchiver, the elog and also the EPICS archiver

**Comment by ZLLentz** [comment]
This should be possible with subclassing the psuedopositioner classes. Will need just a little bit of thought to figure out the best way to pass the args down.

**Comment by klauer** [comment]
I have a general solution in mind. Will propose shortly.

**Comment by klauer** [comment]
Proposal is here: https://github.com/pcdshub/pcdsdevices/pull/508

**Comment by klauer** [comment]
This is ready, but I'm (personally) still unable to deploy new IOCs for each hutch.

However, the latest implementation of this will function seamlessly even if the notepad IOC is not deployed. This circumvents any chicken/egg issues as described in the PR - i.e., deploying the IOC first or the pcdsdevices update first does not matter.

**Comment by silkenelson** [comment]
I think this has been deployed and could be closed? Any reason not to?

**Comment by ZLLentz** [comment]
This has been deployed, I'll close the issue.
