### ISSUE TITLE
MEC: target.left(), target.rigth(), target.up(), target.down()

### ISSUE THREAD

**Issue by egaltier** [pcdshub/Bug-Reports-and-Requests#23]
**Feature Request**

Python commands for moving the target stages to go from target to target (`target.left()`, `target.right()`, `target.up()`, `target.down()`).

**Existing Alternatives**

GUI only.

**Context**

During user beamtime, we have predefined offset to move from target to target on the target cartridges. These values were hardcoded in the past but it would be better to set it via PV variables for example. Using these values in combination to the commands above, we can quickly and accurately move from target to target. In bracket, we usually have an integer as optional value so that we can jump N targets instead of only one: `target.left(3)` means move to the third target that is on the left of the current position, while `target.left()`means move to the closest target on the left.

**Comment by ZLLentz** [comment]
Is the context here an xy stage stack? If so I assume we would just need to configure how far apart targets are. Or is there an MEC target IOC that needs to be integrated?

**Comment by slactjohnson** [comment]
I'm pretty sure we have a class for this already. I think I just need to dig it up and instantiate it for them.

**Comment by egaltier** [comment]
The old way we had to do it was to set a vertical and horizontal separation value which was, unfortunately, hard-coded in the python definition. And since we had different cartridges we had to change those values from time to time. This was really not the right way to do it so whatever approach you think is more sustainable will work for us. One way I can think of is that if we set a default value as parameters for the functions, which would let the option to change it live and whenever is needed. This default value would be set by a PV or a configuration file (or whatever makes more sense).

**Comment by ZLLentz** [comment]
From the Python point of view it is easiest to implement the options as PVs, since reading PVs is very built-in to the Device architecture. This has an advantage where you can easily set them from Python. The cost is that we have some more PVs to manage on a server somewhere. I'll defer to Tyler on this one.

**Comment by slactjohnson** [comment]
Any reason not to have these values stored as class attributes or properties? IIRC this is how I did it in the not-yet-dug-back-up class I alluded to above. These are also easily modified from python and don't require a new IOC.

**Comment by ZLLentz** [comment]
Class attributes don't persist between sessions is the only reason. It may be totally fine to maintain the SOP of editing your beamline file every time you want to configure this, it's up to you.

**Comment by slactjohnson** [comment]
True, though I don't think these values change during an experiment often; it's primarily a function of the target stage stack and alignment. My thinking here was that the target stage stack may be different for each experiment, and the target class, along with target spacings, would be updated in the experiment.py file. Perhaps @egaltier can comment?

**Comment by egaltier** [comment]
Right, the target spacing is usually the same within an experiment. However, our alignment cartridge has shorter spacing. We don't literally shoot on the calibration cartridge so we don't have to worry with damaging nearby targets and we save user target space at the same time. But we could have few ways to work around this:

1) changing the spacing of our alignment cartridge (least favorite, since we would loose some user target space)
2) have a `calibrant.next()` type function, for example, where the spacing would be fixed and set independently of the target user spacing
3) just don't bother for this spacing and use calibrant presets to get to those

I think I prefer option 3 since the presets are just better in this case and we can use the `target.tweak()` type of command to fine tune the position on the calibrant. For example:

1) save the current target holder position with a `target.save_position()` command, for example
2) type `yag()` or `pinhole()` to get to the calibrant you want
3) once you are on the calibrant you use a `target.tweak()` command to tune the position and take the calibration data
4) when done, type a `target.return_position()` which would bring you back to the shot location

So indeed you would not have to change the spacing within an experiment but rather between experiments (if needed).

**Comment by slactjohnson** [comment]
@egaltier I like this solution. 

@silkenelson I think that a class like this could be generally useful across all hutches, though I'm not that familiar with how the rest of HXR operates. Do you see a use case for something like this elsewhere? I'm wondering if we should have a target.py module or similar for defining common target stage stack implementations. I'm not aware of anything like this in pcdsdevices right now. @ZLLentz?

**Comment by ZLLentz** [comment]
Nothing like this exists in pcdsdevices right now, there is a glaring lack of generic xy or xyz stacks in general. I'm fine with all these different ways of implementing the spacing, if the attributes are most convenient and hit all your use cases then go for it.

**Comment by slactjohnson** [comment]
@ZLLentz OK, thanks for confirming. I can work on some stacks that could fit this case, and submit to pcdsdevices. Input from @silkenelson on desired features beyond what's discussed above would be welcomed.

**Comment by silkenelson** [comment]
I believe we have an experiment coming up in XPP where we will be scanning targets in x/y, so anything that can be used to do this would be good. What we are looking for in that case are tools to help us align the motion so that we can then go from target to target in both directions using e.g. a grid-scan.
Henrik had some very old python code that saved the to-be-shot and shot positions in a file that you could load e.g. after an aborted run and continue to shoot on the remaining samples. That is more optional.
I have also seen CXI code that did something that could be implmented this way (I'm thinking the mass of imprint code).
