### ISSUE TITLE
elog post tag

### ISSUE THREAD

**Issue by egaltier** [pcdshub/Bug-Reports-and-Requests#24]
**Bug Report**

The tag option of the `elog.post()` function seems to results in a tag in the elog with each individual letters being a tag instead of the whole word itself.

Example of elog bug with the word `rep rate` as entered in the python command `elog.post('text', tags='rep rate')`:
<img width="1147" alt="Capture d’écran 2020-08-15 à 8 42 31 PM" src="https://user-images.githubusercontent.com/44449282/90326061-9473c880-df38-11ea-966a-39ff81d6f86c.png">

**Expected Behavior**

When adding the option `elog.post('text', run=3, tags='tag')` I would expect the word `tag` to appear in a single word in the web elog and not being separated by `|`.

**Context**

Pushing elog entries from python is faster than going to the elog itself in some cases, especially when reporting status changes for example. Having the tags not working properly will decrease the benefits of creating an entry that can be search latter for debugging or analysis.

**Steps To Reproduce**

1. In python, type `elog.post('text', run=3, tags='tag')`
2. In the web based elog of the experiment (testing it using mecc00118), the post appears with the run number and tags, but the tag seems to have each letter separated by a pipe `|`

**Your Environment**

Typing `mecpython`in command line from mecopr.

**Comment by silkenelson** [comment]
I've pointed this out to Murali and he'll look into this.

**Comment by slacmshankar** [comment]
The API expects you to pass in a list of tags. So, to pass in a single tag one can use [ singletag ]. I will change the code to handle cases where a list is not passed.

**Comment by slacmshankar** [comment]
I have pushed a fix to elog V1.0.1

**Comment by slacmshankar** [comment]
Seems to work with the fix
>>> el.post("Testing from controls log client")
>>> el.post("Testing from controls log client", tags=["test"])
>>> el.post("Testing from controls log client", tags="test")

**Comment by ZLLentz** [comment]
I will start the mass-tagging process that proceeds a conda release. Should be available late today or early tomorrow if things go well.

**Comment by ZLLentz** [comment]
@slacmshankar the elog module tag was not uploaded, because the automated tests failed with a 403 forbidden error on `test_pswww_notebooks[ws-auth]`

See automated tests here: https://travis-ci.com/github/pcdshub/elog/jobs/372516003#L2840

Does this indicate a problem with the code, or a problem with the tests?
