### ISSUE TITLE
Add lxt motors

### ISSUE THREAD

**Issue by klauer** [pcdshub/Bug-Reports-and-Requests#27]
**Feature Request**
* Figure out what `lxt` motors are, what hutches need them, and where they were implemented previously
* Add `lxt` support to pcdsdevices

Feature requests or further information about these devices would be appreciated here.

**Comment by klauer** [comment]
OK, so far, I've discovered `lxt` exists in XCS and XPP only. 

There are a bunch of similarly defined motors:

XCS
* `lxt`
* `txt`
* `lxt_new`
* `lxt_ttc`

XPP
* All from XCS
* `lxt_pump`

Is the scope of this ticket all of these? Any idea what any of them stand for?

**Comment by ZLLentz** [comment]
lxt = Laser xray timing, maybe? I recall these being delay stages that increase/decrease the path length of the laser pulse to change the timing.

Not 100% on which ones are in scope and which are most important.
