### ISSUE TITLE
Shared Plans Repo with Daq Configuration Tools, Common Macros

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/Bug-Reports-and-Requests#31]
**Feature Request**

- Use `nabs` or create new repository for holding shared bluesky plans to be used in all the experimental end stations.
- Include tools for configuring the DAQ inside a plan, e.g. a mutator that adds `yield from daq.configure(<stuff>)` and appropriate arguments.

**Existing Alternatives**

Homebrew

**Context**

We want to share these sorts of things between hutches to reduce duplication and help keep uniformity.

**Comment by klauer** [comment]
👍 on using `nabs`.

`yield from daq.configure(...)` -> `yield from bps.configure(daq, ...)` https://github.com/bluesky/bluesky/blob/master/bluesky/plan_stubs.py#L661

Could this also support the sequencer if they pass one in with the det list? I still don't fully understand it, so feel free to ignore my potentially dumb question.

**Comment by ZLLentz** [comment]
The sequencer is set up to run at every step if passed in as a det, which is great for the 90% use case. We could theoretically extend this to configure the sequencer if the user passes in a list of sequencer rows.

**Comment by ZLLentz** [comment]
This also should be where we define plan inspection tools that are daq-aware and otherwise tooled to the LCLS experience.

**Comment by ZLLentz** [comment]
Requested features from board card:
- return to original position
- return peak
- optional stay

**Comment by klauer** [comment]
I'm curious what `create macros file` is - the others seem pretty clear.

**Comment by klauer** [comment]
Relevant upstream support:

* Create macros file: (?)
* Return to original position: [reset_positions_wrapper](https://github.com/bluesky/bluesky/blob/9f7efffa84009bf4b2ab6324f30aa338402c27d1/bluesky/preprocessors.py#L1078)
* Move to peak: [PeakStats](https://github.com/bluesky/bluesky/blob/9f7efffa84009bf4b2ab6324f30aa338402c27d1/bluesky/callbacks/fitting.py#L174-L176), maybe [tune_centroid](https://github.com/bluesky/bluesky/blob/9f7efffa84009bf4b2ab6324f30aa338402c27d1/bluesky/plans.py#L729) (I was sure there was something more pre-made here, but I'm failing to find it)
* Optional stay: [input_plan](https://github.com/bluesky/bluesky/blob/9f7efffa84009bf4b2ab6324f30aa338402c27d1/bluesky/plan_stubs.py#L539-L553) (prompt user for input during plan)

**Comment by ZLLentz** [comment]
As opposed to plans, which run through the run engine, macros kind of just... do things. When scientists write these sorts of things and decide they are useful for experiment setup, it may be nice to locate them centrally.

**Comment by klauer** [comment]
Bump - seems like this could be closed, or more TODOs could be moved to nabs itself?

**Comment by ZLLentz** [comment]
I think this can be broken up into nabs/hutch-python TODOs, I will try to do so

**Comment by ZLLentz** [comment]
Actually I think it was just two, we can probably close this in favor of those
