### ISSUE TITLE
new python object 'lcls' to query machine status

### ISSUE THREAD

**Issue by dlzhu** [pcdshub/Bug-Reports-and-Requests#33]
This is somewhat related to the old lclslinac and the lclsevent objects. The idea is to have in python an easy way to find out:

- machine ebeam energy, charge, photon energy setting, reprate, undulator K values, tapering settings, peak current, ...
- query/control BYKIK
- know the status of soft hard beam sharing
- setup burst request
- vernier settings and control
- maybe features others use but we don't yet know about.
- ...

**Comment by ZLLentz** [comment]
We have some of these in existing code. We can go through your list, add the missing items, and add an `lcls` object to each hutch's python sessions.

For reference, the relevant classes that we'd need to expand and deploy currently live here: https://github.com/pcdshub/pcdsdevices/blob/master/pcdsdevices/beam_stats.py

**Comment by silkenelson** [comment]
<from requests file - under development>
In[0]: lcls
Out[0]:
LCLS LINAC STATUS
bunch charge: 			180 		[pC]
repetition rate:			120 		[Hz]
ebeam energy: 			10.75 	[GeV]
Vernier energy:			-35 		[MeV]
Photon Energy: 			9.91 		[keV]
BC2 peak current: 		3201 		[A]
electron bunch length:	23 		[fs]
Last eLoss Scan: 		0.93 		[mJ]

**Comment by cristinasewell** [comment]
I have been trying to gather PVs that we need for the LCLS LINAC STATUS and honestly I still don't know for sure what PVs exactly we'll want - I found many PVs that could be relevant. Here is what I came up with:

https://github.com/pcdshub/pcdsdevices/blob/ae61a2448131c40b858a865308b7032995a481c2/pcdsdevices/beam_stats.py#L102-L149

I might be missing some PVs, and I also might (most likely) have extra PVs that we are not interested in. 

@dlzhu  - when you get a chance, I would really like some feedback here to know whether I have the correct PVs and which ones I should keep, and which ones I am still missing - Thank you in advance 😊
