### ISSUE TITLE
Hide or Resolve Yaml Deprecation Warnings

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/Bug-Reports-and-Requests#36]
**Bug Report**

yaml deprecation warning for dask and distributed in every python session with current pcds-3.3.4

**Expected Behavior**

No warnings!

**Context**

Annoyingly, these are actually fixed in the upstream libraries.

**Comment by klauer** [comment]
This is fixed in 3.3.5 - we were pinned to _very_ old dask/distributed leading to these warnings:

```
$ /reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/bin/python -c 'import dask'
/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.4/lib/python3.6/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
$ /reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.5/bin/python -c 'import dask'
$
```

**Comment by ZLLentz** [comment]
https://github.com/pcdshub/pcds-envs/issues/143

I'll add the info about 3.3.5 to the linked card

**Comment by ZLLentz** [comment]
Ah I misread this, disregard comment.

**Comment by ZLLentz** [comment]
If this is fixed in latest we can close this and the other card

**Comment by ZLLentz** [comment]
Confirmed that opening `hutch-python` in latest does not raise these messages
