### ISSUE TITLE
QStandardPaths: XDG_RUNTIME_DIR not set

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/Bug-Reports-and-Requests#40]
**Bug Report**

This prints for me on any ipython session that sets up the qt backend for matplotlib, interfering with the first line of input.
It is very annoying, and affects the hutch python sessions.

**Expected Behavior**

I don't even care if Qt is doing something weird, I don't have to know about it... we want this to not print, either by solving the issue or hiding the warning.

**Comment by hhslepicka** [comment]
What do you have on:
```
env | grep XDG
```

And 
```
export -p | grep XDG
```

?

**Comment by ZLLentz** [comment]
```
zlentz@psbuild-rhel7-01:~$ env | grep XDG
XDG_SESSION_ID=1520
XDG_RUNTIME_DIR=/run/user/14059

zlentz@psbuild-rhel7-01:~$ export -p | grep XDG
declare -x XDG_RUNTIME_DIR="/run/user/14059"
declare -x XDG_SESSION_ID="1520"
```
It's not clear that I still have this problem, my hutch-python session did not complain at all today...

**Comment by hhslepicka** [comment]
Probably that got fixed at the OS level.

**Comment by klauer** [comment]
I'm curious how these variables get injected into the environment (ssh/PAM?) - but it does happen automatically, regardless of X forwarding settings or ssh-agent settings.

<details>
<summary>Poking around</summary>

```
[klauer@psdev02  klauer]$ env |grep XDG
XDG_SESSION_ID=30849
XDG_RUNTIME_DIR=/run/user/14884

[klauer@psdev02  klauer]$ loginctl show-user klauer
Name=klauer
Timestamp=Wed 2020-09-30 11:37:44 PDT
TimestampMonotonic=11616235242400
RuntimePath=/run/user/14884
Slice=user-14884.slice
Display=30849
State=active
IdleHint=no
IdleSinceHint=0
IdleSinceHintMonotonic=0
Linger=no

[klauer@psdev02  klauer]$ loginctl session-status
           Since: Wed 2020-09-30 11:37:44 PDT; 3min 23s ago
          Leader: 10848 (sshd)
          Remote: ...
         Service: sshd; type tty; class user
           State: active
            Unit: session-30849.scope
                  ├─10848 sshd: klauer [priv]
                  ├─10854 sshd: klauer@pts/101
                  ├─10855 -bash
                  ├─11569 loginctl session-status
                  └─11570 loginctl session-status
```
</details>

My best guess here is that your variables got _unset_ somehow, rather than failed to be set initially.

**Comment by ZLLentz** [comment]
I think I'm going to close this for now, re-open if it pops up again
