### ISSUE TITLE
move xpp3 to new versions

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/Bug-Reports-and-Requests#49]
xpp3 is currently using dev/pcds-3.3.3

latest is pcds-3.4.0

should also use local harddrive install

**Comment by ZryletTC** [comment]
All HXR hutches are now running 3.4.0
Haven't done local install yet (but it still seems pretty fast :) )

**Comment by ZLLentz** [comment]
For what it's worth, all the control room machines have it installed locally so it's just a matter of changing the env files

**Comment by ZryletTC** [comment]
Oh, I didn't notice that. Thank you!

**Comment by silkenelson** [comment]
Is this not done? Or just not for all hutches?

**Comment by ZryletTC** [comment]
Oops, it is. But we also have had a new release since then that hasn't been switched to yet. Unless there's something that we need/want now, I'll switch after the next release, which I expect will include pcdshub/pcdsdevices#691
