### ISSUE TITLE
Make an Ophyd Objects for an MPOD channels

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/Bug-Reports-and-Requests#50]
**Feature Request**
I would like an object for an MPOD channels which can set &read the voltage, read the current and switch the channels on/off. For HV channels, also support rise&fall rates. 

**Existing Alternatives**
I have hacked something together in experiment files (e.g. xppx42118)

**Context**
I had to hack something together in experiment files. One example is the use of the mpod channel as bias for a diodes which needed to be scanned.

**Comment by ZLLentz** [comment]
Adding supplementary info, from the mentioned experiment file:
```
class MpodChannel(Device):
    voltage = Cpt(EpicsSignal, ':GetVoltageMeasurement', write_pv = ':SetVoltage', kind='normal')
    current = Cpt(EpicsSignalRO, ':GetCurrentMeasurement', kind='normal')
    state = Cpt(EpicsSignal, ':GetSwitch', write_pv = ':SetSwitch', kind='normal')
    #0 means no EPICS high limit.
    voltage_highlimit =  Cpt(EpicsSignal, ':SetVoltage.DRVH', kind='normal')
```
edm screens at `/reg/g/pcds/epics/ioc/common/mpod/R2.2.3/mpodScreens` as a good place to harvest/compare PVs

Probably need separate classes based on channel type
