### ISSUE TITLE
Questionnaire: function to create epicsArch file

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/Bug-Reports-and-Requests#52]
**Feature Request**
We should make a text file to be read by the DAQ 'epics-archiver' with the defined aliases&PV from the questionnaire

**Existing Alternatives**
Make that text file by hand

**Context**
We or the scientists create these files by hand. This allows us to make mistakes and duplicates some effort.

**Comment by ZLLentz** [comment]
Some supplementary info, example epicsArch file (created by hand):
`/cds/group/pcds/dist/pds/xcs/misc/epicsArch_xcslp0615.txt`
```
* det_x
XCS:USR:MMN:08.RBV

* injector_sam_x
XCS:USR:MMS:17.RBV
* injector_sam_y
XCS:USR:MMS:18.RBV
* injector_sam_z
XCS:USR:MMS:19.RBV
* injector_slit_top_x
XCS:USR:MMS:20.RBV
* injector_slit_top_y
XCS:USR:MMS:21.RBV
* injector_slit_bottom_x
XCS:USR:MMS:22.RBV
* injector_slit_bottom_y
XCS:USR:MMS:23.RBV
* injector_nav_zoom
XCS:USR:MMS:29.RBV
* injector_nav_focus
XCS:USR:MMS:30.RBV
* det_x
XCS:USR:MMN:08.RBV
* BS_x
XCS:USR:MMN:07.RBV
* BS_y
XCS:USR:MMN:06.RBV
* BS_z
XCS:USR:MMN:05.RBV
```
