### ISSUE TITLE
Questionnaire: add/fix creation of Beckhoff axis

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/Bug-Reports-and-Requests#53]
**Bug Report**
Thee questionnaire reading of the motors will create an IMS object for a Beckhoff axis as these are also called "MMS".

**Expected Behavior**
It should create a Beckhoff Axis. We can make it a rule to put "Beckhoff" to the stage-identifier field.

**Context**
I cannot import the con Hamos Y motor from the questionnaire for lv68

**Steps To Reproduce**
xpp3 for xpplv6818, compare von_hamos_y to x.vh_y_DONOTUSEE

**Your Environment**
See above.

**Comment by klauer** [comment]
Closed by https://github.com/pcdshub/happi/pull/181
